name: share-ubuntu

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Runner to use'
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      CYM_TOKEN:
        required: false

jobs:
  ubuntu-job:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: complate swoole
        run: |
          sudo apt update
          sudo chmod 777 /mnt
          sh swoole/alpine318version.sh
      - name: move file
        run: |
          mkdir file
          if compgen -G "/mnt/swoole-cli-main318/*-linux-x64.tar.xz" > /dev/null; then
            mv /mnt/swoole-cli-main318/*-linux-x64.tar.xz file/
          else
            echo "No x64 tar.xz files found to move"
          fi

          if compgen -G "/mnt/swoole-cli-main318/*-linux-arm64.tar.xz" > /dev/null; then
            mv /mnt/swoole-cli-main318/*-linux-arm64.tar.xz file/
          else
            echo "No arm64 tar.xz files found to move"
          fi
      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.CYM_TOKEN }}
          tag: v1
          file_glob: true
          overwrite: true
          #release_name: v 自动发布
          file: file/*
